DROP DATABASE IF EXISTS userappSqlDb;
CREATE DATABASE userappSqlDb;
DROP TABLE IF EXISTS usersapp;

CREATE TABLE usersapp(
    user_app_id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL
);